-- V1 베이스라인 (UV-57) — 2026-09-09 시점 엔티티(P1~W7, UV-41~56)와 1:1 대응하는 정식 DDL.
-- 이전까지 ddl-auto=update로 생성돼 온 스키마를 그대로 옮긴 것이며, 이 파일은 수정하지 않는다.
-- 이후 스키마 변경은 V2__*.sql 이상으로만 추가한다 (엔티티 변경 → 마이그레이션 파일 → ddl-auto=validate로 검증).
-- 기존 개발 DB는 baseline-on-migrate로 V1이 "적용된 것으로" 표시되고, 빈 DB는 이 파일이 실행된다.

-- ── 조직 (UV-50) ─────────────────────────────────────────────────────────────
create table team (
    id                    varchar(64)  not null,
    name                  varchar(255) not null,
    region                varchar(255) not null,
    account_manager_name  varchar(255),
    account_manager_email varchar(255),
    -- MailConfig embedded (UV-56): 고객사 SMTP, 비밀번호는 AES-GCM 암호문만
    smtp_host             varchar(255),
    smtp_port             integer,
    smtp_use_tls          boolean,
    smtp_username         varchar(255),
    smtp_password_enc     varchar(512),
    smtp_from_address     varchar(255),
    mail_domain           varchar(255),
    created_at            timestamp(6) with time zone not null,
    constraint pk_team primary key (id)
);

create table project (
    id                          varchar(64)  not null,
    team_id                     varchar(64)  not null,
    name                        varchar(255) not null,
    type                        varchar(16)  not null,
    time_zone                   varchar(64)  not null,
    region_name                 varchar(255),
    license_plan                varchar(255),
    license_channel_limit       integer,
    license_expires_at          date,
    smtp_host                   varchar(255),
    smtp_port                   integer,
    smtp_use_tls                boolean,
    smtp_username               varchar(255),
    smtp_password_enc           varchar(512),
    smtp_from_address           varchar(255),
    mail_domain                 varchar(255),
    network_isolated_detected   boolean      not null default false,
    network_isolated_override   boolean,
    compute_instance            varchar(255),
    gpu_count                   integer,
    model_version               varchar(255),
    created_at                  timestamp(6) with time zone not null,
    constraint pk_project primary key (id),
    constraint ck_project_type check (type in ('SMART_CITY', 'SMART_SCHOOL'))
);

-- ── 계정·세션 (UV-47/50/51/56) ──────────────────────────────────────────────
create table user_account (
    id                       bigint generated by default as identity,
    account_id               varchar(64)  not null,
    email                    varchar(255),            -- 사번 전용 계정은 null (UV-51)
    employee_id              varchar(64),
    name                     varchar(255) not null,
    role                     varchar(255) not null,
    team                     varchar(255) not null,   -- 표시용 팀명 (team_id와 별개, 프로필 계약 호환)
    team_id                  varchar(64),
    password_hash            varchar(128) not null,
    permission               varchar(16)  not null default 'NONE',
    app_access               boolean      not null default true,
    app_search               boolean      not null default false,
    status                   varchar(16)  not null default 'ACTIVE',
    must_set_password        boolean      not null default false,
    temp_password_issued_at  timestamp(6) with time zone,
    setup_code_hash          varchar(64),
    setup_code_issued_at     timestamp(6) with time zone,
    invite_token_hash        varchar(64),
    invite_token_issued_at   timestamp(6) with time zone,
    last_login_at            timestamp(6) with time zone,
    created_at               timestamp(6) with time zone not null,
    constraint pk_user_account primary key (id),
    constraint uk_user_account_account_id  unique (account_id),
    constraint uk_user_account_email       unique (email),
    constraint uk_user_account_employee_id unique (employee_id),
    constraint ck_user_account_permission check (permission in ('OWNER', 'ADMIN', 'AUDITOR', 'NONE')),
    constraint ck_user_account_status     check (status in ('ACTIVE', 'INVITED', 'SUSPENDED'))
);

-- @ElementCollection user_project (계정별 접근 가능 프로젝트)
create table user_project (
    user_id    bigint not null,
    project_id varchar(64),
    constraint fk_user_project_user foreign key (user_id) references user_account (id)
);

create table user_session (
    token_hash     varchar(64) not null,             -- 세션 토큰 SHA-256, 원문은 쿠키에만
    user_id        bigint      not null,
    keep_logged_in boolean     not null,
    user_agent     varchar(256),
    ip             varchar(64),
    created_at     timestamp(6) with time zone not null,
    expires_at     timestamp(6) with time zone not null,
    last_seen_at   timestamp(6) with time zone,
    constraint pk_user_session primary key (token_hash)
);

-- 로그인/코드 시도 카운터 (UV-51): key = "login:{identifier}" | "code:{ip}"
create table auth_attempt (
    key          varchar(200) not null,
    failures     integer      not null,
    window_start timestamp(6) with time zone not null,
    locked_until timestamp(6) with time zone,
    constraint pk_auth_attempt primary key (key)
);

-- 이메일 코드 비밀번호 재설정 (UV-56): 사용자당 진행 중 1건
create table password_reset (
    id                  bigint generated by default as identity,
    user_id             bigint      not null,
    code_hash           varchar(64) not null,
    attempts            integer     not null,
    resends             integer     not null,
    created_at          timestamp(6) with time zone not null,
    last_sent_at        timestamp(6) with time zone not null,
    expires_at          timestamp(6) with time zone not null,
    verified_at         timestamp(6) with time zone,
    verified_token_hash varchar(64),
    constraint pk_password_reset primary key (id),
    constraint uk_password_reset_user unique (user_id)
);

-- ── 로스터 (UV-51) ──────────────────────────────────────────────────────────
create table staff_roster (
    employee_id    varchar(64)  not null,
    project_id     varchar(64)  not null,
    name           varchar(255) not null,
    department     varchar(255),
    email          varchar(255),
    permission     varchar(16)  not null,
    status         varchar(16)  not null,
    code_hash      varchar(64),                      -- 사용 후에도 유지 (재사용 시 4021 used 판정)
    code_issued_at timestamp(6) with time zone,
    used_at        timestamp(6) with time zone,
    user_id        bigint,
    created_at     timestamp(6) with time zone not null,
    constraint pk_staff_roster primary key (employee_id),
    constraint ck_staff_roster_permission check (permission in ('ADMIN', 'OPERATOR')),
    constraint ck_staff_roster_status     check (status in ('NOT_ISSUED', 'UNUSED', 'USED'))
);

-- ── 카메라 원장 (UV-41/42/43/53) ────────────────────────────────────────────
create table camera (
    camera_id    varchar(64)  not null,
    project_id   varchar(64),
    code         varchar(32),                         -- CAM-{ZONE3}-{NNN}
    name         varchar(255) not null,
    location_id  varchar(64)  not null,
    location     varchar(255),
    zone         varchar(255),
    lat          float(53)    not null,
    lng          float(53)    not null,
    rtsp_url     varchar(512) not null,               -- 관리자 세션에만 노출, 대시보드 공개 계약 금지
    protocol     varchar(8),
    username     varchar(255),
    password_enc varchar(512),                        -- AES-GCM 암호문, 응답은 hasCredential만
    ip           varchar(255),
    mac          varchar(255),
    maker        varchar(255),
    model        varchar(255),
    resolution   varchar(255),
    server_id    varchar(64),
    ai_features  varchar(256),                        -- csv
    thumbnail    varchar(512),
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null,
    constraint pk_camera primary key (camera_id)
);

-- 상태 전이 이력 (UV-53): MQTT cameras/{id}/status 적재, 전이 시에만 1행
create table camera_status_history (
    id        bigint generated by default as identity,
    camera_id varchar(64) not null,
    status    varchar(16) not null,
    at        timestamp(6) with time zone not null,
    constraint pk_camera_status_history primary key (id)
);
create index ix_cam_status_cam_at on camera_status_history (camera_id, at);

-- 시간별 감지 집계 (UV-56): MQTT detections 버퍼 → 10초 flush upsert
create table detection_hourly (
    id        bigint generated by default as identity,
    camera_id varchar(64) not null,
    hour_utc  timestamp(6) with time zone not null,
    total     integer not null,
    vip       integer not null,
    vehicle   integer not null,
    unknown   integer not null,
    constraint pk_detection_hourly primary key (id),
    constraint uk_detection_hourly_camera_hour unique (camera_id, hour_utc)
);

-- ── 서버 레지스트리 (UV-53) ─────────────────────────────────────────────────
create table server (
    id              varchar(64)  not null,
    project_id      varchar(64)  not null,
    name            varchar(255) not null,
    type            varchar(32)  not null,
    ip              varchar(255) not null,
    port            integer,
    specification   varchar(255),
    status          varchar(16)  not null,
    last_checked_at timestamp(6) with time zone,
    last_error      varchar(255),
    created_at      timestamp(6) with time zone not null,
    constraint pk_server primary key (id)
);

-- ── 감사 로그 (UV-50) ───────────────────────────────────────────────────────
create table audit_event (
    id            bigint generated by default as identity,
    project_id    varchar(64),
    actor_user_id bigint,
    actor_name    varchar(255) not null,
    message       varchar(512) not null,
    at            timestamp(6) with time zone not null,
    constraint pk_audit_event primary key (id)
);
create index ix_audit_project_at on audit_event (project_id, at);
