-- V2 (UV-59) — 인물 검색 감사 기록. 기획 확정 2026-09-09 "기획이 정한 6건" 8번:
--   대상 이미지 원본은 보관하지 않는다(SHA-256 해시·크기·개수만). 사진을 보관하면 감사 기록이 그 자체로
--   개인정보 보관처가 되고, "같은 사진으로 다시 찍었나"는 해시로 확인된다.
--   보관 기간은 검색 기록만 1년(운영 감사 로그 audit_event는 무기한) — "누가 누구를 찾았나"가 무기한 쌓이면
--   직원 행동 기록이 된다. 기간은 vca.admin.search-audit-retention-days(설치별 env)로 조정.
create table search_audit (
    id            bigint generated by default as identity,
    at            timestamp(6) with time zone not null,
    user_id       bigint       not null,
    user_name     varchar(255) not null,
    account_id    varchar(64)  not null,
    project_id    varchar(64),                 -- 행위자 배정 프로젝트가 정확히 1개일 때만 귀속 (앱은 프로젝트 개념 없음)
    feature       varchar(32)  not null,       -- redmap | reid | track | redface
    endpoint      varchar(128) not null,       -- 브라우저가 부른 프록시 경로
    criteria      varchar(4000),               -- 쿼리·텍스트 파트·JSON 본문 (이미지 바이트 제외)
    image_sha256  varchar(64),                 -- 첫 이미지 파트 해시. 원본은 저장하지 않는다
    image_bytes   bigint,
    image_count   integer      not null default 0,
    result_count  integer,
    duration_ms   integer,
    status        varchar(16)  not null,       -- ok | error
    error_code    varchar(32),
    ip            varchar(64),
    constraint pk_search_audit primary key (id)
);
create index ix_search_audit_project_at on search_audit (project_id, at);
create index ix_search_audit_at on search_audit (at);
